### ISSUE TITLE
Some items not working on Minemenu

### ISSUE THREAD

**Issue by Danymaddox** [dmillerw/MineMenu#10]
Hi! I found that the following items does not work when I try to open it with Minemenu:
- Chisel from Chisel 0.0.2.6
- Chiseled Bit Bag from Chisel & bits

**Comment by GirafiStudios** [comment]
What exact step would you need to reproduce this ? :)

**Comment by Danymaddox** [comment]
First i hold "r", select an empty space and click on it, set a title and an icon, click on action and select use item, select Chisel and done.

I don't speak english a lot and I understood that's what you need ^^

Thank you :D

**Comment by GirafiStudios** [comment]
Hmm okay. I see the problem, I will look into it :)

**Comment by Danymaddox** [comment]
Thanks! Awesome work! ^^

**Comment by GirafiStudios** [comment]
Mentioned in https://github.com/dmillerw/MineMenu/issues/11. Keeping that opening for reference and clsoing this :)
