### ISSUE TITLE
[Enhancement] Alternate Keybind system

### ISSUE THREAD

**Issue by Zsashas** [dmillerw/MineMenu#13]
In addition to selecting a keybind function from the binding menu, what about a second option to simply press a key and have it use that? Would work for things that aren't found in the vanilla menu, like Modular Powersuits keybinds.

**Comment by GirafiStudios** [comment]
I'm not familiar with how Modular Powersuits do their keybinds.
I don't see any reason for a mod to not register their keybindings, especially now that Forge allows you to register keybindings with Ctrl and Shift.
If you can give me any example of a 1.10 mod, where this would be useful I will reconsider :)

**Comment by Zsashas** [comment]
Another use for this would be hotkeys for multiple functions at once, as if the actual key were being pressed. Like say I have a bunch of mod HUDs toggle visibility with the same key, I can't do the same with MineMenu.
