### ISSUE TITLE
1.7.10 Port (unable to open gui)

### ISSUE THREAD

**Issue by Garrom** [dmillerw/MineMenu#14]
can you please port version 1.3+ of the mod on 1.7.10 versions of the game.

There is still a lot of people who play 1.7.10 and the bug that makes it impossible to open the gui makes mod unusable.

 
Pleeeeeeeease, only one backport, you do that a lot of people happy

_ps. sorry for bad English. I am Czech. you have no idea how hard it is to translate such a short text_

**Comment by GirafiStudios** [comment]
By "the gui" you mean Mine Menus radial menu, or?

**Comment by Garrom** [comment]
@GirafiStudios 
No, I mean any button form mods that use graphic elements.
For example, "Add Waypoint" from Xareos minimap mod or "Inventory" from flans mod.
But buttons as a "Change item mode" from Mekanism mod also does not work because it uses graphic elements (animation of 3D model).
All these buttons when using,Closes the radial menu and the cursor lose focus on the game.
I looked at the changelog, version 1.3 has this bug fixed. Unfortunately, version 1.3 is up to 1.8.9.
On version 1.7.10 it is not fixed

**Comment by Garrom** [comment]
@GirafiStudios
I do not require all the features.
just fix the bug :)

**Comment by GirafiStudios** [comment]
Looking at the 1.3 changelog it does not actually fix this problem. Only thing it fixes is that trying to open any GUI that it can't it sets Minecraft to unfocused.
If I ever get around to actually fix the problem I will consider backporting it :)

**Comment by Garrom** [comment]
Well, thanks for the info.
Now I can do nothing else but wait ...
