### ISSUE TITLE
Bug? Commands that open other windows/overlays fail

### ISSUE THREAD

**Issue by Thiana** [dmillerw/MineMenu#15]
With MineMenu 1.4.4B9 on 1.10.2 it appears that any keybind that would open a new window/overlay simply does nothing. For example, opening JourneyMap or Psi's manual. Thanks.

**Comment by GirafiStudios** [comment]
Thanks for reporting!
This is a known bug, just simply don't have time to fix it currently. Will get around to it eventually :)

**Comment by thephoenixlodge** [comment]
Any chance of this getting fixed? Trying to set up the mod to simplify a lot of confusion with keybinds in Sprout, and a lot of what I'm trying to do outright doesn't work because of this bug.
