### ISSUE TITLE
Bugs in 1.11.2

### ISSUE THREAD

**Issue by NovaViper** [dmillerw/MineMenu#17]
I have a couple bugs I noticed

The toggles key doesn't seem to work as I'm trying to set the sprint and sneak keys, but nothing happens. Also I can't use the menu to spawn animals, right click on things, or use items: i.e. bows, swords, ,fishing rod, etc. (If that's not in, could you add that function in?)

**Comment by Tenember** [comment]
I'm having some troubles too. Most part of the mod doesn't seems to work. And when I try to use it with another mod, for example, opening the Lexica Botania book of Botania, it simply crash.

**Comment by NovaViper** [comment]
I haven't tried using it with mods but it doesn't seem to work

**Comment by NovaViper** [comment]
Hey @GirafiStudios, this issue still persists! Is it ever going to be fixed in 1.11.2?
