### ISSUE TITLE
"Select a Key" only shows the titles of the keys. No buttons to click.

### ISSUE THREAD

**Issue by Knito58** [dmillerw/MineMenu#20]
MC 1.12
Forge 14.21.1.2387
MineMenu 1.12-1.6.1

Buttons gone.

https://www.dropbox.com/s/8sdsres4hy3jawk/MineMenuSelectKey.jpg?dl=1

**Comment by TrialDragon** [comment]
Hello, i have the exact same issue any progress made?

**Comment by dragon3025** [comment]
I'm also having this problem.

**Comment by GirafiStudios** [comment]
I haven't been able to figure out what is causing it yet.

**Comment by GirafiStudios** [comment]
Fixed in https://github.com/dmillerw/MineMenu/commit/9071e2d865b610ef1b6a0d01a3db02ebf284ded5

**Comment by GirafiStudios** [comment]
Fixed in https://github.com/dmillerw/MineMenu/commit/1a8df3a8468fd7d23d14db41c89e8920bb728506
