### ISSUE TITLE
Keystroke shortcuts? (enhancement)

### ISSUE THREAD

**Issue by Kzitold** [dmillerw/MineMenu#21]
Navigating the MineMenus by keystrokes.

Like "menu, 3" for the shortcut in the 3 position, or "menu, 6, 9" for sub-menu in the 6 position and shortcut in the 9 position.

**Comment by GirafiStudios** [comment]
You mean similar to how the vanilla hotbar works?

**Comment by GirafiStudios** [comment]
Closing this, since there haven't been any response in a while.
