### ISSUE TITLE
toggles and clipboard

### ISSUE THREAD

**Issue by WorseWaif** [dmillerw/MineMenu#22]
I have a few commands and keybindings in subcategories, and I keep running into the issue that it switches them to "toggle" or "clipboard" and no matter how many times I try to make them "press" or "send" it will randomly switch them to toggle or clipboard.

**Comment by WorseWaif** [comment]
Ok i just think i found the issue. when I do "shift+setkey" to edit the button, clicking shift while on the button changes the setting, whether it be for clipboard or for toggle.

**Comment by GirafiStudios** [comment]
Thanks for your report!
Unfortunately I can't reproduce the issue. Please provide more information.
