### ISSUE TITLE
Register as Client Side Only Mod

### ISSUE THREAD

**Issue by cjm721** [dmillerw/MineMenu#24]
Currently not registered as a client side only mod but loads client side only classes by default. If was intended to be both sides need to move that binding to Client proxy.

` java.lang.NoClassDefFoundError: net/minecraft/client/settings/KeyBinding`

**Comment by GirafiStudios** [comment]
MineMenu is not a client-side only mod. But you are right the key binding should indeed only be loaded on the client. A fix should be up later on CurseForge.

**Comment by TechnosophyModPack** [comment]
Why isn't it a client-side only mod?

**Comment by GirafiStudios** [comment]
Because it's doing stuff that interacts with the world, like "using" an item in a specific slot. As of 1.14 commands can not be done on the client only anymore.
