### ISSUE TITLE
Trouble with schematica mod

### ISSUE THREAD

**Issue by Ignaramico** [dmillerw/MineMenu#25]
When I use the linked key for schematica mod schematic selection on minemenu it gets kind of "stuck", it opens normaly (the schematic selection menu) but it cant be closed since it reopens again forcing one to reestart the client.
I made sure to try differents keys and verified that it as on press and not toggle

**Comment by GirafiStudios** [comment]
Known issue. Not sure when I will have time to take a look at fixing it though.
