### ISSUE TITLE
Missing documentation / wiki

### ISSUE THREAD

**Issue by metabuddy** [dmillerw/MineMenu#26]
Hi,
Could not find any documentation or instructions on how to use this mod, except for the brief description on curse forge. Is there some more info?

**Comment by GirafiStudios** [comment]
There is more information on the Minecraft Forum post: http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2141720-minemenu-v1-2-0-radial-menu-nuff-said
