### ISSUE TITLE
 New feature

### ISSUE THREAD

**Issue by LastSpectral1** [dmillerw/MineMenu#27]
I'm here to ask a little feature that where on the screen generates a place to type and function as an additional field for the wheel functions! giving an example for this is for the teleport where the command would be / tpa <field>

**Comment by GirafiStudios** [comment]
Thanks for your suggestion!
There is already a way to add a button to the wheel with a command, isn't that what you are asking for?

**Comment by LastSpectral1** [comment]
I think I was misinterpreted! I wanted to say a way to be able to put a field where the player can enter an extra command next to the command that is already placed initially by the owner of the modpack project! as I gave the example of the teleport that needs the name to teleport, my idea is to press on the button of the wheel, that opens a field in the middle of the screen to type!
I do not know if I understood, because I'm using the translator
