### ISSUE TITLE
Crash when typing in searchbar to select item to display for menu

### ISSUE THREAD

**Issue by mahilo3550** [dmillerw/MineMenu#29]
Whenever I attempt selecting another item as the display for a menu slot, pressing on any key crashes my game. Scrolling does not seem to do anything, so how am I going to be able to use any item NOT on that first page for display? MC 1.12.2 Forge: 14.23.1.26.10 Minemenu: 1.6.3.

**Comment by GirafiStudios** [comment]
Thanks for you report!
Nothing I can do about this with a crash report, so please provide that.
But this is most likely caused by some mod adding Null-items. I know Buildcraft have caused this issue in the past, so if you have that installed that might be the issue.
