### ISSUE TITLE
Issue With Iron Backpacks (MineCraft version 1.12.2)

### ISSUE THREAD

**Issue by MaxAstro** [dmillerw/MineMenu#30]
Assigning an Iron Backpack to a "use item" menu button results in the backpack opening with only a single slot, unless you are currently holding the backpack in your hands when you use the menu item.

**Comment by GirafiStudios** [comment]
Nothing I can do about that. It is how Iron Backpacks are coded - the GUI can only be opened when the backpack is in the hand.
