### ISSUE TITLE
Unable to open Journey Map using this.

### ISSUE THREAD

**Issue by Kzitold** [dmillerw/MineMenu#37]
I bind Journey Map full screen map to Mine Menu, and it doesn't open. Really need it for Vivecraft since my buttons are limited.

**Comment by GirafiStudios** [comment]
Thanks for the report!
Making stuff like this would require a major rewrite of the mod, which I simply do not have time to do.

**Comment by ItsDeltin** [comment]
I made a workaround:
https://github.com/ItsDeltin/keysim/tree/master
Set the Mine Menu option to do a command like "/keysim gui.xaero_open_map" which will open the Xaero fullscreen map. It seems to work with everything.
