### ISSUE TITLE
I cant delete bindings/commands from the radial menu

### ISSUE THREAD

**Issue by Z3r0ut3** [dmillerw/MineMenu#39]
More information: I cant delete bindings/commands from the radial menu. I have aktivated the option "rightclick to edit" for deleding commands but it doesent work.. I have to edit the json to delete commands..

**Comment by GirafiStudios** [comment]
You are giving me nothing to go of?
What Minecraft version are you using? What MineMenu version are you using?

**Comment by Z3r0ut3** [comment]
Iam using 1.12.2 and the newest version from the mod MineMenu-1.12.2-1.6.3-universal.jar

**Comment by GirafiStudios** [comment]
I really can't reproduce the issue. It even updates the json right away for me.
Only thing I can think of is that you are editing them wrong? By default you have to hold shift, then clicking on the icon to open up the edit menu.
GIF of me successfully deleting both types of buttons from the radial menu: https://i.imgur.com/5Tj8ixo.gifv
