### ISSUE TITLE
Client Crash 1.12.2 

### ISSUE THREAD

**Issue by AngelusQQ** [dmillerw/MineMenu#47]
https://pastebin.com/DY4hXCMG

Forge Version: 2768
Minecraft Version: 1.12.2

Crashes when Minecraft loads MineMenu during the Preinitialization Phase.

**Comment by GirafiStudios** [comment]
Are you using just Forge on the client, or Sponge Forge?

**Comment by AngelusQQ** [comment]
I am using just Forge on the client
Sponge Forge for the Server; Server loads fine
last working version of MineMenu for me is "MineMenu-1.12.2-1.6.4-universal"

I could of sworn it the latest set of updates were working after 1.6.4 were working on my client; but it is possible I saw the server crash first and disregarded the client's status.

![TEMP](https://user-images.githubusercontent.com/30601131/54496676-99a69100-48c8-11e9-9946-712405e4a8b6.png)

**Comment by GirafiStudios** [comment]
No it's cause of a change I made in the last build, to make it work in my dev environment. It works on the latest versions of Forge just fine. But if I remember correctly, Sponge Forge requires you to use the recommended version of Forge, right?

**Comment by AngelusQQ** [comment]
Correct, Sponge uses the Recommended Version of Forge (14.23.5.2768)

**Comment by GirafiStudios** [comment]
I'll release a new version that works properly on older builds then.
Forge really needs to come out with a new recommended build, 14.23.5.2768 is ancient.
I'll upload it to CurseForge in a few minutes, please let me know if it works for you :)

**Comment by AngelusQQ** [comment]
Works perfectly; Thank you for your time and effort! <3
