### ISSUE TITLE
Manually Editing menu.json makes the file unusable. 

### ISSUE THREAD

**Issue by mahilo3550** [dmillerw/MineMenu#50]
Whenever I had attempted to edit/add anything to the menu.json file manually, the game would no longer be able to use the file and I’d have to start over from scratch. I saw in Changelog 1.6.5 for 1.12.2 it states the menu.json now reloads with F3+T shortcut “for easy editing manually”. Does this mean the menu.json is now capable of being edited? Could you show us an example of this being done?

**Comment by GirafiStudios** [comment]
You can edit the menu.json just fine, as long as you keep to the proper format. Best way of learning is to add stuff to the radial menu in-game, and see what it writes to the menu.json.
