### ISSUE TITLE
Remove the zoom-in effect

### ISSUE THREAD

**Issue by Finelarme9** [dmillerw/MineMenu#52]
Hello
Thank you for this mod. Is it possible for you to remove the zoom-in effect when we open the HUD please ? This update would be amazing for the 1.12 version.
Ben

**Comment by GirafiStudios** [comment]
Thank you for your report
Mine Menu does not have any zoom-in effect. Must be some other mod perhaps using the same keybind to do some sort of zoom effect?

**Comment by Finelarme9** [comment]
Sorry. I meant there is a kind of effect when you open the GUI, it's not like instant visible. I will make a gif to explain it better lol.

**Comment by GirafiStudios** [comment]
Oh, I thought you meant the Minecraft world zoomed in, when opening Mine Menu.
I'll take a look at it in a couple of days, currently don't have access to a computer I can easily code on.

**Comment by Finelarme9** [comment]
No problem man. Here is a gif of my problem to understand better : https://giphy.com/gifs/ZZqDbUpEVfGqn4H7U3/html5 (sorry for the quality). I would like to not have this effect "zoom" when I open/close the menu.

**Comment by GirafiStudios** [comment]
Yea I understand you now.
I'll add a config option when I get time.

**Comment by Finelarme9** [comment]
Sure. Thank you in advance :).

**Comment by Finelarme9** [comment]
Also. Do you think that you can find a way to make the stone blocks (in the menu) customizable (allow to choose the blocks ID for each sections I mean) ? I have seen the option "removeStoneOnMenuButton" but it only removes the blocks i guess. I'm gonna check that now.
