### ISSUE TITLE
MAtmos key binding does not survive relaunch of minecraft

### ISSUE THREAD

**Issue by aetherknight** [dmillerw/MineMenu#7]
I am able to add a key binding for MAtmos, a liteloader mod, that opens its configuration menu (MAtmos defaults it to F7 for its menu). When I quite Minecraft, I see the entry in the MineMenu json file. However, upon relaunching Minecraft and resuming my world, the MAtmos entry in the radial menu is gone. I can then re-add it again until I start the game again.

I am loading liteloader as a Forge coremod (placing it in `mods/1.7.10/liteloader-1.7.10-03.jar`), if the ordering of when mods are loaded has an impact on when MineMenu determines which keybindings exist.

### Versions

* Mac OS X 10.10.1
* Java 7 1.7.0_71
* Minecraft 1.7.10
* Forge 10.13.2.1230
* MineMenu 1.2.0.B44
* Liteloader 1.7.10-03
* MAtmos r28b http://minecraft.ha3.eu/matmos/download.php

**Comment by aetherknight** [comment]
One additional observation: The `MineMenu/menu.json` file does not remove the matmos entry until I make some change to the MineMenu menus, even when the entry does not show up after relaunching Minecraft.

**Comment by Brycey92** [comment]
I believe this is MAtmos' fault, since it resets the keybinding upon relaunch whether or not MineMenu is installed.

**Comment by GirafiStudios** [comment]
If it's in the menu.json after relaunch it's not Mine Menus fault :)
